name: Create release PR

run-name: Create release PR for new ${{ github.event.inputs.version }} version

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: choice
        description: 'What type of release is this'
        options:
          - 'major'
          - 'minor'
          - 'patch'

jobs:
  create-release-pr:
    name: Create release PR
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      VERSION: ''
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '22'
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.work'
          cache-dependency-path: ${{ github.workspace }}/src/go.sum
      - name: Generating version changes
        env:
          GH_TOKEN: ${{ secrets.BUILD_PAT }}
        run: |
          git config --global user.email "cjlapao@gmail.com"
          git config --global user.name "cjlapao"

          VERSION=$(make bump-${{ inputs.version }})
          echo "$VERSION" > ./VERSION

          git checkout -b release/v"$VERSION"

          # TODO: Uncomment this when we have a way to run the swagger generation
          # go install github.com/swaggo/swag/cmd/swag@latest
          # cd src
          # go mod tidy
          # swag fmt
          # swag init -g main.go
          # cd ..

          # Generate changelog for the new version
          make changelog

          # TODO: Uncomment this when we have a way to run the helm chart build
          # Generate Helm Chart
          # make build-helm-chart

          git add VERSION CHANGELOG.md ./docs/charts/* ./docs/_posts/* ./src/* ./badges/* 
          git commit -m "Release extension version v$VERSION"

          git push --set-upstream origin release/v"$VERSION"

          echo "VERSION=$VERSION" >> "$GITHUB_ENV"

      - name: Create PR
        run: |
          make release-changelog
          gh pr create \
            --title "Release version ${{ env.VERSION }}" \
            --body-file release_notes.md \
            --base main \
            --head release/v${{ env.VERSION }}
          gh pr edit --add-label release-request
        env:
          GH_TOKEN: ${{ secrets.BUILD_PAT }}
